defaults:
  - backend: pytorch

hydra:
  run:
    dir:
      outputs/${experiment_id}/${instance_id}
  sweep:
    dir: outputs/${experiment_id}/${instance_id}
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"

python_version: ${python_version:}
model: bert-base-cased
batch_size: 1
sequence_length: 128
benchmark_duration: 5
warmup_runs: 5
device: cpu
precision: float32
num_instances: 1
num_core_per_instance: -1